### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by hardingnj** [evotools/hapbin#13]
Hi there,

This is a fantastic tool, thank you. A release would be really helpful to ensure that current and future analyses are running with the same version of the code. 

Thanks!

**Comment by prenderj** [comment]
Hi Nick

Thanks, that's a good idea. Neil who has permissions to do this is away but
we will do this next week.

**Comment by npch** [comment]
Hi Nick,

I have created a release v1.0.0 of the code. This is the same version that we've used for the comparisons against selscan in the [paper in MBE] (http://dx.doi.org/10.1093/molbev/msv172).

Thanks for the suggestion and do let us know if you have any other feedback from using the tool.

**Comment by hardingnj** [comment]
Thanks for this. A -v/--version flag in the cla would be helpful I think?
