### ISSUE TITLE
VCF support - or conversion script?

### ISSUE THREAD

**Issue by jewmanchue** [evotools/hapbin#15]
Hi Neil,

I have some large beagle-phased VCF files I would like to run through HapBin.  Do you have VCF support?

**Comment by prenderj** [comment]
Hi Zev

It is a bit buried in the README but you can convert from VCF to impute format using VCFtools with the --impute flag.

http://vcftools.sourceforge.net/man_latest.html#OUTPUT%20OPTIONS

Cheers
James

**Comment by jewmanchue** [comment]
thanks.
