### ISSUE TITLE
loci with MAF>X reporting does not seem to work

### ISSUE THREAD

**Issue by hardingnj** [evotools/hapbin#17]
The loci that are reported is 3316 as suggested in the log. However, loci may be unreported for other reasons, ie EHH fails to decay to the minimum. 

However, the other unreported loci seem to be lumped in with the ones that fail the MAF threshold. 

A breakdown of # SNPs and why not reported would be very useful.

```
Chromosomes per SNP: 100
Threads: 8

1000/10983
2000/10983
3000/10983
4000/10983
5000/10983
6000/10983
7000/10983
8000/10983
9000/10983
10000/10983
Calculations took 954.247ms
# loci with MAF >= 0.05: 3316
```

This notebook shows 8445 SNPs >= 0.05. I have no idea why the rest of the SNPs are missing?

https://gist.github.com/hardingnj/3b22af3df74142c11ea1

**Comment by camaclean** [comment]
Hapbin does the following:

    double maxEHH = ret.num/(double)hapmap->snpLength();
    if (!(maxEHH <= 1.0 - m_minMAF && maxEHH >= m_minMAF))
    {
        ++(*outsideMaf);
        return EHH();
    }

I have also added counters for NaN results and calculations which hit the end of the chromosome.

**Comment by camaclean** [comment]
Oh, it looks like that this is an inclusive compare, too, so there's a discrepancy there. I had changed the test to match Selscan's behavior but forgot to update the output text.

**Comment by hardingnj** [comment]
Many thanks for the quick fix!
