### ISSUE TITLE
Print iHH0, iHH1, iHHA, and iHHB

### ISSUE THREAD

**Issue by stephenrong** [evotools/hapbin#20]
Is there a way to print the intermediate iHH0, iHH1, iHHA, and iHHB values for computing iHS and XPEHH?

**Comment by prenderj** [comment]
Hi

At present these aren't output. But it would be relatively easy to fork the code and adapt it to output these. For example for iHS these are stored in the ehh.iHH_d and ehh.iHH_a variables in ihsfinder.cpp so would just need to print these.

Hopefully that helps

James
