### ISSUE TITLE
specify that g++ should be used for compilation

### ISSUE THREAD

**Issue by ekg** [evotools/hapbin#4]
I've encountered another problem with the build:

```text
~/hapbin/build$ make 
[ 12%] Building CXX object CMakeFiles/hapbin.dir/ehhfinder.cpp.o
cc1plus: error: unrecognised command line option ‘-std=c++11’
make[2]: *** [CMakeFiles/hapbin.dir/ehhfinder.cpp.o] Error 1
make[1]: *** [CMakeFiles/hapbin.dir/all] Error 2
make: *** [all] Error 2
```

I have a version of `g++` in my path that supports `-std=c++11` (version 4.9.2). However, it does not seem to be recognized by cmake and I'm at a loss for how to reconfigure the prebuild to use this compiler.

It may not provide the features of cmake, but sometimes a simple Makefile is easier to work with. Do you have one available?

**Comment by prenderj** [comment]
Hi Erik

I tried building it with g++ 4.9.2 on Ubuntu and it went ok. (Had to grab 4.9.2 from the Ubuntu toolchain)

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9

cd /usr/bin
sudo rm gcc g++ cpp
sudo ln -s gcc-4.9 gcc
sudo ln -s g++-4.9 g++
sudo ln -s cpp-4.9 cpp
cd

sudo apt-get update
sudo apt-get install git cmake libcr-dev mpich libmpich-dev

git clone https://github.com/camaclean/MPIRPC.git
cd MPIRPC/
cd build/
cmake ../src/
make
sudo make install

cd ../../
git clone -b master https://github.com/evotools/hapbin.git
cd hapbin/build/
cmake ../src/
make -j 4
```

As you say sounds like your 4.9.2 version of g++ is not being found. Have you tried specifying the path to g++ and gcc when running cmake? Can use the -DCMAKE_CXX_COMPILER= and -DCMAKE_C_COMPILER= flags. e.g. this works for me

```
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9 ../src/
```

Would just need to make sure pointing to right versions

Cheers
James

**Comment by ekg** [comment]
This worked. I'm experiencing further problems (see #4).
