### ISSUE TITLE
Hapbin Physical Map Info

### ISSUE THREAD

**Issue by paolo002** [evotools/hapbin#49]
Hi, the new hapbin 1.3 version is giving me now 5 columns instead than 2 only which were given by old  version:
Location    iHH_0    iHH_1    iHS std     iHS

Since I am providing map file to calculate iHS, is it possible to have in the output an additional 6th column with the info of the location (from physical or genetic map)? Because the column which here is indicated as "Location" gives the info about the SNP name (ID) but not the exact number of the location (locus ID).

Regards

**Comment by paolo002** [comment]
the same problems occurs when I calculate XPEHH by the way

**Comment by camaclean** [comment]
Hi,

Yeah, I can add an Index column and perhaps rename to Location to SNP_ID to make the distinction clearer.

-Colin

**Comment by paolo002** [comment]
Hi Colin

Yes, please, if possible can you do that?
Last time you added the two columns iHH_0 iHH_1 and the standardised iHS and the XPEHH columns in the output which were very useful. Thanks a lot.
If it is possible to have a column with the SNP ID and then also a column for the correspondent location of the SNP on the genome coming from the input map file given, would be really great.
I think in selscan output that information is provided so it would be great to have in hapbin something similar to that.
Thanks a lot again!
Regards
Paolo

**Comment by camaclean** [comment]
I added the zero-indexed ID. You can then use that to find the corresponding ID in the map file.

**Comment by prenderj** [comment]
Hi Colin

Do you mean variant position minus one? This may be confusing for users.
Actual variant position from the map file would be more useful. Though in
the mean time Paolo if in a hurry can just put SNP position in id.

**Comment by camaclean** [comment]
Well, it is the position, just counting starting from zero the way you would in most programming languages. This way you don't have to do any offset when looking up map[index].

**Comment by paolo002** [comment]
Thank you very much!, having the info about the SNP position in the output is very useful.
If you can update again the version 1.3.0 in the conda repository as you guys did last time it would be great.
