### ISSUE TITLE
Phase III iHS

### ISSUE THREAD

**Issue by jewmanchue** [evotools/hapbin#5]
I'm wondering if the computed iHS values available at: http://datashare.is.ed.ac.uk/handle/10283/714 are corrected by allele frequency?

**Comment by prenderj** [comment]
Hi

Yes, these are standardised iHS. Hapbin spits out unstandardised and standardised by default. 2% frequency bins were used (the default setting in hapbin).

Hopefully that helps

**Comment by jewmanchue** [comment]
Another Q:

Did you filter the phased files on allele frequency before running Hapbin?

**Comment by prenderj** [comment]
Hi

No but the minimum minor allele threshold was left on its default setting -
5%. So these SNPs were excluded by hapbin

**Comment by jewmanchue** [comment]
Thank you for all your help.
