### ISSUE TITLE
Potential bug in iHS calculation for hapbin1.3

### ISSUE THREAD

**Issue by paolo002** [evotools/hapbin#52]
Hi Colin
This is Paolo once again.
I think there is still some problem with the sign in hapbin 1.3 for the calculation of the iHS.
Based on my understanding the iHS value of a SNP should be log(iHH1/iHH0). However in the output of hapbin 1.3 the formula used is -log(iHH1/iHH0). In fact in the XPEHH output is log(iHHA1/iHHB1).

Also, some other question, I am trying to standardise XPEHH output but I can calculate the zscore for each value, I am not sure how to divide in 2% frequency bins. Please, can you let me know how to standardise the XPEHH output because I am not able to use the master branch. Alternatevely, please can you implement the standardisation also for the XPEEH similarly to iHS?

**Comment by camaclean** [comment]
Hi,

The iHS is calculated as ln(iHH0/iHH1). 0 is ancestral and 1 is derived. This is how iHS is defined in the original paper. Keep in mind that ln(x) == -ln(1/x). You have the ancestral and derived reversed. This was the bug I had in 1.0 that has now been fixed.

Why aren't you able to use the master branch? Standardized XPEHH is already implemented there.

-Colin

**Comment by paolo002** [comment]
Hi Colin
I am so sorry, yes I did a mistake in my previous post.
The iHS formula should be log(iHH0/iHH1).
This is my head() of the output

    X         SNP          iHH_0          iHH_1       iHS        Std_.iHS   CHR      BP      rank     rank.perc        P
1   1   rs7072834 2014060.0   2738.52  6.600490 5.68295  10  71380221    1 2.041857e-07 6.689975
2   2  rs11696012 2772120.0   4018.19  6.536540 5.41206   2 141804368    2 4.083714e-07 6.388945
3   3   rs1294888  222899.0   2954.75  4.323300 5.28980   7  45244259    3 6.125571e-07 6.212853

So for instance the first SNP iHS is log(2014060.0/2738.52)=6.600490
That should be correct. I got this output in hapbin 1.3.
So just to ask you, does a positive/high iHS or positive/high Std_iHS mean selection on ancestral allele and a negative/low values mean selection on derived allele? Is this correct? 

I have problems installing the master branch because I am running hapbin on a public server and I don't have permission to install things, (it is a bit troublesome), so I was just using the version I downloaded from conda repository and call it using ./hapbin.
Best
Paolo

**Comment by paolo002** [comment]
```
X        SNP  iHH_0   iHH_1     iHS  Std_iHS CHR        BP    rank rank.perc           P
4372663 4372663  rs7519408 584442 65261.6 2.19225 -2.08876   1 207661289 4372663 0.9816542 0.008041451
4373038 4373038  rs6696840 316950 54698.9 1.75690 -2.09061   1 207819729 4373038 0.9817384 0.008004207
4375785 4375785  rs6659617 314256 54698.9 1.74837 -2.10443   1 207820201 4375785 0.9823551 0.007731483
4388340 4388340  rs7525170 504631 71035.4 1.96065 -2.17558   1 207668447 4388340 0.9851737 0.006487190
4388341 4388341  rs9429942 504631 71035.4 1.96065 -2.17558   1 207668630 4388341 0.9851739 0.006487091
4389177 4389177  rs9429780 504631 71259.1 1.95750 -2.18062   1 207667190 4389177 0.9853616 0.006404364
4389178 4389178  rs9429781 504631 71259.1 1.95750 -2.18062   1 207667222 4389178 0.9853618 0.006404265
4389179 4389179  rs9429941 504631 71259.1 1.95750 -2.18062   1 207667303 4389179 0.9853621 0.006404166
4392097 4392097  rs9429779 504631 72134.0 1.94530 -2.20021   1 207664721 4392097 0.9860171 0.006115536
4392556 4392556  rs9429943 584442 70154.0 2.11997 -2.20341   1 207669924 4392556 0.9861202 0.006070152
4392557 4392557  rs9429944 584442 70154.0 2.11997 -2.20341   1 207670307 4392557 0.9861204 0.006070053
4394165 4394165 rs10863341 584442 70647.4 2.11296 -2.21452   1 207673084 4394165 0.9864814 0.005911098
4394167 4394167  rs4844598 584442 70647.4 2.11296 -2.21452   1 207672612 4394167 0.9864819 0.005910900
4394170 4394170  rs7533408 584442 70647.4 2.11296 -2.21452   1 207673631 4394170 0.9864825 0.005910604
4395343 4395343  rs2182911 499717 72442.7 1.93125 -2.22277   1 207660071 4395343 0.9867459 0.005794687
4395344 4395344  rs2182912 499717 72442.7 1.93125 -2.22277   1 207660344 4395344 0.9867461 0.005794588
4395345 4395345  rs2182913 499717 72442.7 1.93125 -2.22277   1 207660378 4395345 0.9867463 0.005794489
4406924 4406924  rs7533520 504569 77209.5 1.87718 -2.30953   1 207673945 4406924 0.9893458 0.004651898
4407131 4407131  rs4274065 504032 77209.5 1.87612 -2.31125   1 207671476 4407131 0.9893922 0.004631499
4407132 4407132  rs4844597 504032 77209.5 1.87612 -2.31125   1 207671269 4407132 0.9893925 0.004631400
```
This is regarding my previous question. In this case iHS values are positive and quite high but the standardise values are negative. So should I consider selection on which allele?

**Comment by camaclean** [comment]
@prenderj Could you answer the bioinformatics parts of these questions?

@paolo002 My expertise is in high performance computing and the programming side of things, not bioinformatics, so I'm not a reliable source for those questions. I take equations and make things run fast.

Do you have a local computer you can compile on? I don't maintain any of the Anaconda stuff. Someone else went and packaged hapbin. I don't even know who the maintainer is. Do you have a local computer or virtualbox that has a compiler you can use? 

-Colin

**Comment by camaclean** [comment]
I went ahead and made a prelease on my branch and built a binary: https://github.com/camaclean/hapbin/releases/download/v1.4-rc0/hapbin-1.4-rc0-x86_64-pc-linux-gnu.tar.gz

**Comment by paolo002** [comment]
I see, I am sorry Colin for bothering you with all these questions.Maybe is prenderj can answer to those, it will be very useful to me.

I don't have virtual box but currently I am using linux on a personal Mac computer...
In any case, thank you very much for building the binary, that is what I need, I already downloaded and transferred it to the server.
Can I just confirm with you something, in this new version 1.4 that you gave are the XPEHH values already standardised? is that correct?
Regards
Paolo

**Comment by paolo002** [comment]
Hi Colin
There is a problem with the 1.4 version you just gave me.
If I try to run it, it starts correctly but then it throws this error:
Haplotypes in population A: 146
Haplotypes in population B: 210
Illegal instruction

If I try to run the same command but with the 1.3 version is ok...
Haplotypes in population A: 146
Haplotypes in population B: 210
Threads: 24 
69000/20117836

Best
Paolo

**Comment by camaclean** [comment]
Hi Paolo,

Can you tell me the CPU type you are using? Look for "model name" in /proc/cpuinfo. What I built was compiled for the AMD Bulldozer architecture. That error means there's CPU code that your processor doesn't have the instruction set support to run. I'll have to rebuild it to target yours.

-Colin

**Comment by camaclean** [comment]
Also send me the "flags" part of your /proc/cpuinfo

**Comment by camaclean** [comment]
Also, send me the "model name" and "flags" of the /proc/cpuinfo of the server you will be doing production runs on.

**Comment by prenderj** [comment]
Hi Paolo

I wouldnt read too much into the sign of the iHS prior to standardisation.
You should find if you plot the standardised and unstandardised iHS values
against each other they are positively correlated but standardisation
shifts the distribution so its mean is 0. I would plot the distributions of
your values before and after standardisation to get a better idea of what
is happening.

Hope that helps
James

**Comment by paolo002** [comment]
Hi James

I see, I understand. Thank you very much for your advice, I will do that definitely. The reason why I was looking at the sign is that I have found some positive selection signal on a gene based on standardised values of the iHS which later I confirmed by nSL and PBS. So, I wanted to know the sequence of the long haplotype based on the iHS values and in order to determine the sequence I need to know that information. Let me know your advice about this if possible. Thanks a lot.
Regards
Paolo

**Comment by paolo002** [comment]
Hi Colin

The CPU info of the server where I am running hapbin is the following:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz

Is this info enough?
Best,
Paolo

**Comment by paolo002** [comment]
this is what I got under the flags info:

fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm invpcid_single pti retpoline tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm cqm_llc cqm_occup_llc ibpb ibrs stibp

**Comment by camaclean** [comment]
Hi Paolo,

Give this a try: https://github.com/camaclean/hapbin/releases/download/v1.4-rc1/hapbin-1.4-rc1-haswell-linux-pc-gnu.tar.gz

It's built for haswell, which is the architecture of your server. It should run there but I don't know about your laptop.

-Colin

**Comment by paolo002** [comment]
Hi Colin
Thank you very much. I am trying the latest version on the server and it seems to be working now.
I will be using only on the server since our data is very large, I don't think I need to use it on my laptop so that is totally fine. Thank you very much for your work. It is very helpful.
Regards
Paolo

**Comment by paolo002** [comment]
Hi James

Yes, I am aware of the rehh package and the bifurcation plot is something that I need to do. Just that the hapbin output I guess it needs to be modified in order to use it for the rehh package if I am not wrong. But, once again, it would be useful to me to know if there is selection on the reference or alternate allele based on the hapbin output.
Best
Paolo

**Comment by paolo002** [comment]
Hi Colin

I have got the correct output for the XPEHH, thank you so much for implementing the index and the standardised values for the XPEHH. Everything is very good, If you have not done it yet you can release this new hapbin version on this GitHub main page so other people can use since the output file now is much better. Really appreciated your work. Cheers.
Regards
Paolo

**Comment by paolo002** [comment]
Dear Colin

This is Paolo again.

I am sorry to disturb you once again but I am preparing the manuscript with my professor with the hapbin results I have got.

May I know if the sign (+ or -) in the column of the standardized iHS values relates to the signal of selection on the alternate/reference allele?
We can only determine the selection signal (if towards REF or ALT) from the sign of the non standardized iHS values, is that correct?
What does the sign of the standirdized values mean then?
Does it mean that if positive is significant or if negative is not significant?

Your answer would be very helpful to us.
Thanks
Regards
Paolo
________________________________
