### ISSUE TITLE
avoid system-wide installation of mpirpc?

### ISSUE THREAD

**Issue by ekg** [evotools/hapbin#6]
I'm attempting to build and link mpirpc.

I'd like to avoid system-wide installation as there doesn't seem to be a way to uninstall it (`make uninstall` doesn't seem to be part of the generated cmake makefile). So I build with this:

```sh
cmake -DMPIRPC_DIR=/home/erik/src/MPIRPC/build/CMakeFiles/Export/lib/cmake/mpirpc/ ../src/
```

And I get:

```text
CMake Error at /home/erik/src/MPIRPC/build/CMakeFiles/Export/lib/cmake/mpirpc/MPIRPCConfig.cmake:72 (message):
  The imported target "mpirpc" references the file

     "/home/erik/src/MPIRPC/build/CMakeFiles/Export/lib/libmpirpc.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/erik/src/MPIRPC/build/CMakeFiles/Export/lib/cmake/mpirpc/MPIRPCConfig.cmake"

  but not all the files it references.
```

Is there any way to build without installing mpirpc system wide?

This might be really important if the user doesn't have root access. (In fact, there are other issues in that case with the dependencies that are required...)

**Comment by camaclean** [comment]
You need to install MPIRPC somewhere. First, set the install prefix when building MPIRPC. For instance, you could install into `$HOME/install/`:

    cd MPIRPC/src/build
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/ ..
    make
    make install

This will install MPIRPC into `$HOME/install/`

Now, tell Hapbin where to find MPIRPC:

    cd hapbin/src/build
    cmake -DCMAKE_PREFIX_PATH=$HOME/install/ ..
    make

**Comment by prenderj** [comment]
Hi

I think this may still spit out an error as cant find .hpp files. Can fix this by just adding the corresponding folder to the CPATH variable but Colin may have a better idea than this. So if want to install MPIRPC locally to MPIRPC/install directory in your home directory:

```
git clone https://github.com/camaclean/MPIRPC.git
cd MPIRPC/build/
cmake -DCMAKE_INSTALL_PREFIX=$HOME/MPIRPC/install/ ../src/
make
sudo make install

export CPATH=$HOME/MPIRPC/install/include:$CPATH

cd ../../
git clone -b master https://github.com/evotools/hapbin.git
cd hapbin/build/
cmake -DCMAKE_PREFIX_PATH=$HOME/MPIRPC/install/ ../src/
make -j 4

**Comment by camaclean** [comment]
I submitted a pull request which will allow CMake to find the include directories. You'll need to update MPIRPC, too.

**Comment by prenderj** [comment]
Have added example of how to install without root permissions to README

**Comment by npch** [comment]
I believe that this issue is now resolved in the latest version of hapbin. Please feel free to reopen the issue if it isn't working for you, and provide a copy of any compilation errors.
