### ISSUE TITLE
non standardised versus standardised

### ISSUE THREAD

**Issue by paolo002** [evotools/hapbin#60]
Hi 

Do the sign ( + or -) in the iHS standardised column correspond to selection on REF/ALT allele similarly to the non standardized iHS column or it is just a measure of how do the values deviate from the mean? if + means significant if - non significant?

**Comment by prenderj** [comment]
Hi

I would suggest checking the original iHS paper for how to interpret the
standardised iHS results.

https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0040072


But in brief significance isnt determined by sign. Standardised iHS
represent how many standard deviations a particular variant's
unstandardised iHS is above (if positive) or below (if negative) the mean
of other variants in the genome in the same allele frequency bin. They are
therefore analogous to the standard score:

https://en.wikipedia.org/wiki/Standard_score

 Cheers
James

**Comment by paolo002** [comment]
Thanks a lot for the clear explanation
