### ISSUE TITLE
iHS Results Interpretation

### ISSUE THREAD

**Issue by YingLi13** [evotools/hapbin#66]
Hi~
I‘ve completed iHS analysis, but I don't really understand the results.
1. Why some iHS  values is negative
2. Compara to iHS values, Std iHS is more significant for selective signal identified？

**Comment by prenderj** [comment]
Hi

I would suggest having a read of the original paper that describes the iHS
statistic (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1382018/). This
will illustrate why have negative values (e.g. see Figure 4) and the
difference between the standardised and unstandardised iHS values
